name: teamsta
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  badges: ^2.0.3
  bubble: ^1.2.1
  cupertino_icons: ^1.0.2
  debug_overlay: ^0.2.0
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_native_image: ^0.0.6+1
  flutter_toggle_tab: ^1.2.0
  geolocator: ^9.0.1
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  google_geocoding: ^0.2.0
  google_maps_flutter: ^2.1.8
  google_place: ^0.4.7
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lottie: ^1.4.1
  maps_launcher: ^2.0.1
  search_map_location: ^0.0.6
  tuple: ^2.0.0
  unicons: ^2.1.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# Run these commands in terminal for this to work
# also import flutter_launcher_icons
#! flutter pub get
#! flutter pub run flutter_launcher_icons:main run in terminal
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/androidIcon.png'
  image_path_ios: 'assets/icons/iosIcon.png'
  # adaptive_icon_background: '#ffffff'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
