List<String> teamServices = [
  "All categories",
  "Attractions",
  "Friendly match request",
  "Gym",
  "Individual sport",
  "Leisure Activity",
  "Personal trainer",
  "Photographer",
  "Physio",
  "Referee",
  "Sports gear",
  "Team sport",
  "Tournament",
  "Venue",
  "Videographer",
  "Other Business",
];
//! they exactly the same but in future may be different
List<String> userServices = [
  "All categories",
  "Attractions",
  "Gym",
  "Individual sport",
  "Leisure Activity",
  "Personal trainer",
  "Photographer",
  "Physio",
  "Referee",
  "Sports gear",
  "Team sport",
  "Venue",
  "Videographer",
  "Other Business",
];
