List<String> categories = [
  "All categories",
  "Acrobatics",
  "Activities: Fishing",
  "Activities: Gaming",
  "Activities: Karaoke",
  "Activities: Laser Tag",
  "Activities: Minigolf",
  "Activities: Soft play centre",
  "Activities: Trampoline",
  "Activities:Paintball",
  "Aerobic Gymnastics",
  "Archery",
  "Artistic Gymnastics",
  "Artistic Swimming",
  "Athletics",
  "Badminton",
  "Baseball",
  "Basketball",
  "Baton Twirling",
  "Bicycle Motocross (BMX)",
  "Billiards/ Pool (U.S.)",
  "Bobsleigh",
  "Bodybuilding",
  "Bowling",
  "Boxing",
  "Canoeing",
  "Car Racing",
  "Cheerleading",
  "Cricket",
  "Croquet",
  "cross country running",
  "Curling",
  "Dance Sport",
  "Darts",
  "Diving",
  "Dodgeball",
  "Fencing",
  "Figure Skating",
  "Football",
  "Frisbee",
  "Golf",
  "Gymnastics",
  "Handball",
  "Hang Gliding",
  "Hiking",
  "Hockey",
  "Horse Racing",
  "Horseback Riding",
  "Ice Hockey",
  "Ice Skating",
  "Jet Ski Racing",
  "Judo",
  "Karate",
  "Kayaking",
  "Kendo",
  "Kick Boxing",
  "Kite Surfing",
  "Lacrosse",
  "Luge",
  "Mixed Martial Arts",
  "Motocross",
  "mountain running",
  "Muay Thai",
  "Paintball",
  "Parachuting",
  "Paragliding",
  "Parkour",
  "Polo",
  "Pool/Billiards",
  "Powerlifting",
  "race walking",
  "Rafting",
  "Rhythmic Gymnastics",
  "road running",
  "Rock Climbing",
  "Rowing",
  "Rugby",
  "Sailing",
  "Sandboarding",
  "Scuba Diving",
  "Shooting",
  "Skateboarding",
  "Skeleton",
  "Skiing",
  "Snowboarding",
  "Soccer",
  "Softball",
  "Speed Skating",
  "Sport Climbing",
  "Squash",
  "Sumo Wrestling",
  "Surfing",
  "Swimming",
  "Synchronized Skating",
  "Synchronized Swimming",
  "Table Tennis",
  "Taekwondo",
  "Tennis",
  "track and field",
  "Track and Field",
  "trail running",
  "Tug of War",
  "Volleyball",
  "Water Polo",
  "Weightlifting",
  "Windsurfing",
  "Wrestling",
  "Other",
];

// list for the users
List<String> searchCategories = [
  "All categories",
  "Acrobatics",
  "Activities: Fishing",
  "Activities: Gaming",
  "Activities: Karaoke",
  "Activities: Laser Tag",
  "Activities: Minigolf",
  "Activities: Soft play centre",
  "Activities: Trampoline",
  "Activities:Paintball",
  "Aerobic Gymnastics",
  "Archery",
  "Artistic Gymnastics",
  "Artistic Swimming",
  "Athletics",
  "Badminton",
  "Baseball",
  "Basketball",
  "Baton Twirling",
  "Bicycle Motocross (BMX)",
  "Billiards/ Pool (U.S.)",
  "Bobsleigh",
  "Bodybuilding",
  "Bowling",
  "Boxing",
  "Canoeing",
  "Car Racing",
  "Cheerleading",
  "Cricket",
  "Croquet",
  "cross country running",
  "Curling",
  "Dance Sport",
  "Darts",
  "Diving",
  "Dodgeball",
  "Fencing",
  "Figure Skating",
  "Football",
  "Frisbee",
  "Golf",
  "Gymnastics",
  "Handball",
  "Hang Gliding",
  "Hiking",
  "Hockey",
  "Horse Racing",
  "Horseback Riding",
  "Ice Hockey",
  "Ice Skating",
  "Jet Ski Racing",
  "Judo",
  "Karate",
  "Kayaking",
  "Kendo",
  "Kick Boxing",
  "Kite Surfing",
  "Lacrosse",
  "Luge",
  "Mixed Martial Arts",
  "Motocross",
  "mountain running",
  "Muay Thai",
  "Paintball",
  "Parachuting",
  "Paragliding",
  "Parkour",
  "Polo",
  "Pool/Billiards",
  "Powerlifting",
  "race walking",
  "Rafting",
  "Rhythmic Gymnastics",
  "road running",
  "Rock Climbing",
  "Rowing",
  "Rugby",
  "Sailing",
  "Sandboarding",
  "Scuba Diving",
  "Shooting",
  "Skateboarding",
  "Skeleton",
  "Skiing",
  "Snowboarding",
  "Soccer",
  "Softball",
  "Speed Skating",
  "Sport Climbing",
  "Squash",
  "Sumo Wrestling",
  "Surfing",
  "Swimming",
  "Synchronized Skating",
  "Synchronized Swimming",
  "Table Tennis",
  "Taekwondo",
  "Tennis",
  "track and field",
  "Track and Field",
  "trail running",
  "Tug of War",
  "Volleyball",
  "Water Polo",
  "Weightlifting",
  "Windsurfing",
  "Wrestling",
  "Other",
];
